export const MOCKUP_DEX_ENTRY = {
  _name: "Neutral",
  _id: 0,
  _description: "Neutral",
  _types: [{ id: 1, name: "normal" }],
  _evolution_id: "0000-0000-0000",
  _evolution_lvl: 0,
  _atk_min: 0,
  _atk_max: 0,
  _def_min: 0,
  _def_max: 0,
  _hp_min: 0,
  _hp_max: 0,
  _spd_min: 0,
  _spd_max: 0,
  _moves: [
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
  ],
  _is_starter: false,
};
