export const MOCKUP_DEX_ENTRY = {
  name: "Neutral",
  id: 0,
  description: "Neutral",
  types: [{ id: 1, name: "normal" }],
  evolution_id: "0000-0000-0000",
  evolution_lvl: 0,
  atk_min: 0,
  atk_max: 0,
  def_min: 0,
  def_max: 0,
  hp_min: 0,
  hp_max: 0,
  spd_min: 0,
  spd_max: 0,
  moves: [
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
    {
      name: "Neutral",
      damage: 0,
      type: { id: 1, name: "Neutral" },
      crit: { success: 0, fail: 0 },
    },
  ],
  is_starter: false,
};
